---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: dryrun
  pull: always
  image: plugins/docker:latest
  settings:
    repo: toolhippie/calens
    tags: amd64
    dockerfile: Dockerfile.amd64
    dry_run: true
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:latest
  settings:
    repo: toolhippie/calens
    tags: amd64
    dockerfile: Dockerfile.amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      exclude:
      - pull_request

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: arm32v6

platform:
  os: linux
  arch: arm

steps:
- name: dryrun
  pull: always
  image: plugins/docker:latest
  settings:
    repo: toolhippie/calens
    tags: arm32v6
    dockerfile: Dockerfile.arm32v6
    dry_run: true
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:latest
  settings:
    repo: toolhippie/calens
    tags: arm32v6
    dockerfile: Dockerfile.arm32v6
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      exclude:
      - pull_request

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: arm64v8

platform:
  os: linux
  arch: arm64

steps:
- name: dryrun
  pull: always
  image: plugins/docker:latest
  settings:
    repo: toolhippie/calens
    tags: arm64v8
    dockerfile: Dockerfile.arm64v8
    dry_run: true
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:latest
  settings:
    repo: toolhippie/calens
    tags: arm64v8
    dockerfile: Dockerfile.arm64v8
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      exclude:
      - pull_request

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  pull: always
  image: plugins/manifest:1
  settings:
    spec: manifest.tmpl
    ignore_missing: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**

depends_on:
- amd64
- arm32v6
- arm64v8

---
kind: pipeline
name: notification

platform:
  os: linux
  arch: amd64

steps:
- name: microbadger
  pull: always
  image: plugins/webhook:1
  settings:
    urls:
      from_secret: microbadger_url
  when:
    status:
    - success

- name: notify
  image: plugins/matrix:1
  pull: always
  settings:
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
  when:
    status:
    - failure

depends_on:
- amd64
- arm32v6
- arm64v8
- manifest

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**

...
